### ISSUE TITLE
fails to require vue-select

### ISSUE THREAD

**Issue by raftalks** [Haixing-Hu/vue-select#2]
Hi,

I tried using this library and it seems to me when doing require('vue-select') no longer works as it is globally named as 'vue-select2' on package.json file.

You may need to update the readme file.

If I do require('vue-select2') it does work however throws an error with tools like browserify
as the expected value of the key "main" in the package.json file is expected to have string instead of any array.

Can you please check https://github.com/Haixing-Hu/vue-select/blob/master/package.json#L18-L20
and it should be 

```
main: "./src/vue-select.js"

Thanks
```

**Comment by silverark** [comment]
@raftalks, did you manage to get this to work? I'm still getting the error regarding the array rather than a string

**Comment by Haixing-Hu** [comment]
Fixed in the current version.
