### ISSUE TITLE
Why twoWay on model?

### ISSUE THREAD

**Issue by Namek** [Haixing-Hu/vue-select#8]
When using [Vuex ](https://github.com/vuejs/vuex/)(redux-like thing) the two-way binding approach isn't really supported or expected. That's why I would rather depend on one-way `model` and `@change` event in this situation.

Is there any specific reason to enforce `twoWay` or could we remove that constraint?

**Comment by Haixing-Hu** [comment]
If the user change the selection, the value of model in the component will be changed. And we want the value of the variable bound to the model outside the component also be changed according to the user selection. That's why we need two-way binding.
